[tool.poetry]
name = "pakistan-project"
version = "0.1.0"
description = ""
authors = ["blessedmadukoma <blessedmadukoma@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
fastapi = "^0.115.12"
boto3 = "^1.37.34"
python-dotenv = "^1.1.0"
black = "^25.1.0"
uvicorn = "^0.34.1"
pandas = "^2.2.3"
sqlalchemy = "^2.0.40"
awscli = "^1.38.37"


[tool.poetry.group.dev.dependencies]
black = "^25.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
